/*
 * This source file was generated by the Gradle 'init' task
 */
package com.repo.analyzer;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appInstantiates() {
        PolyglotApp classUnderTest = new PolyglotApp();
        assertNotNull(classUnderTest, "app should instantiate");
    }
}
