/*
 * This source file was generated by the Gradle 'init' task
 */
package com.repo.analyzer;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appHasGreeting() {
        // Simple smoke test to ensure main class loads
        PolyglotApp classUnderTest = new PolyglotApp();
        assertNotNull(classUnderTest, "app should have a greeting");
    }
}
